#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cd /app || exit 1

# Node report flags require a pre-existing directory writable by `abc`.
s6-setuidgid abc mkdir -p /config/crash-reports

exec \
    s6-setuidgid abc \
    node \
        --enable-source-maps \
        --report-on-fatalerror \
        --report-uncaught-exception \
        --report-directory=/config/crash-reports \
        dist/server/index.js
