// Alphabetical lowercase names shared by settings and metadata validation; keep
// aligned with KNOWN_NAMES in core/utils/language-codes.ts.
export const CANONICAL_LANGUAGES = [
  'arabic',
  'bulgarian',
  'catalan',
  'chinese',
  'croatian',
  'czech',
  'danish',
  'dutch',
  'english',
  'estonian',
  'finnish',
  'french',
  'german',
  'greek',
  'hebrew',
  'hindi',
  'hungarian',
  'italian',
  'japanese',
  'korean',
  'latvian',
  'lithuanian',
  'norwegian',
  'polish',
  'portuguese',
  'romanian',
  'russian',
  'serbian',
  'slovak',
  'slovenian',
  'spanish',
  'swedish',
  'thai',
  'turkish',
  'ukrainian',
  'vietnamese',
] as const;

export type CanonicalLanguage = (typeof CANONICAL_LANGUAGES)[number];
